export default {
  server_url : 'https://i5b106.p.ssafy.io:5000/',
  nav_show: true,
  start_page_tomato_show: false,
  isLogin : false,
  studyInfo : '',
  studyComments : [],
  studyImg : '',
  studyData: [],
  studyDataSpeci: '',
  totalTomato : '',
  studyTomato : '',
  myInfo : {},
  checkflag: '',
  tomatoes: [],
  myTomato: '',
  everyTomato: '',
  myStudyTime: [],
  myRecentStudy: [],
  studyHashtag: [],
  searchedStudies: [],
  totalPage: 1,
  participants: [],
  participantsInfo : [],
  studyPomodoroGoals: [],
  studyPomodoroState: [],
  blacklist: [],
  temp_tomato_info: []

}